# Generated by Django 3.0.1 on 2021-09-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app120', '0003_auto_20210908_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='password',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
